<a href="https://colab.research.google.com/github/VarunSharma02/Numpy_codes/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#Creating rank-1 arrays

In [ ]:
an_array = np.array([3, 33, 333,  3333, 33333])

In [ ]:
print(type(an_array))
print(an_array)
print(an_array.shape)
print(an_array[0], an_array[1], an_array[2])

<class 'numpy.ndarray'>
[    3    33   333  3333 33333]
(5,)
3 33 333


In [ ]:
# array are mutable
an_array[0] = 888
print(an_array)

[  888    33   333  3333 33333]


In [ ]:
an_array[0] = "Hi"
print(an_array)

ValueError: invalid literal for int() with base 10: 'Hi'

#Rank-2 Array

In [ ]:
another = np.array([[11,12,13],[21,22,23]])
print(another)
print(type(another))
print(another.shape)
print(another[0,0], another[0,1],another[1,0])

[[11 12 13]
 [21 22 23]]
<class 'numpy.ndarray'>
(2, 3)
11 12 21


In [ ]:
a1 = np.array([[1,2,3]])
print(a1)
print(a1.shape)

[[1 2 3]]
(1, 3)


In [ ]:
ex1 = np.zeros((2,2))
ex1= ex1+1.2
print(ex1)
print(ex1[0,0])

[[1.2 1.2]
 [1.2 1.2]]
1.2


In [ ]:
ex2 = np.full((2,2), 9.1)
print(ex2)

[[9.1 9.1]
 [9.1 9.1]]


In [ ]:
ex3 = np.eye(5,5)#.astype("int64")
print(ex3)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
ex4 = np.ones((1,2))
print(ex4)

[[1. 1.]]


In [ ]:
ex5 = np.random.random((2,2))
print(ex5)